n2mobile/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from home.views import home_view
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',home_view, name='home'),
    url(r'^post/', include('post.urls')),
]

post/urls.py
from django.conf.urls import url
from .views import *

app_name = 'post'

urlpatterns = [

    url(r'^index/$', post_index, name='index'),
    url(r'^(?P<id>\d+)/$', post_detail, name='detail'),
    url(r'^create/$', post_create, name='create'),
    url(r'^(?P<id>\d+)/update/$', post_update, name='update'),
    url(r'^(?P<id>\d+)/delete/$', post_delete, name='delete'),
]

home/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models
from django.urls import reverse


# Create your models here.

class Post(models.Model):

    name = models.CharField(max_length=120, verbose_name='adınız')
    surname = models.CharField(max_length=120,verbose_name='Soyadınız')
    recorded_date = models.DateTimeField(verbose_name='Kayıt Tarihi', auto_now_add=True)
    department =models.ForeignKey("Department", verbose_name='departman')

    def __unicode__(self):
        return "{0} {1}".format(self.name,self.surname)

    def get_absolute_url(self):
        return reverse('post:detail',kwargs={'id':self.id})

        #return "/post/{}".fomat(self.id)

    def get_create_url(self):
        return reverse('post:create')

    def get_update_url(self):
        return reverse('post:update',kwargs={'id':self.id})

    def get_delete_url(self):
        return reverse('post:delete',kwargs={'id':self.id})

    class Meta:
        ordering = ['-recorded_date','id']

class Department(models.Model):

    department_name = models.CharField(max_length=50)

    def __str__(self):
        return self.department_name

post/forms.py
from django import forms
from .models import Post,Department

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = [
            'name',
            'surname',
            'department',


        ]

home/views.py
from django.shortcuts import render,HttpResponse


def home_view(request):
    if request.user.is_authenticated:
        context = {
            'isim':'Emre',
        }
    else:
        context ={
            'isim':'Misafir'
        }


    return render(request,'home.html',context)

post/views.py
from django.shortcuts import render,HttpResponse, get_list_or_404, HttpResponseRedirect, redirect, Http404,get_object_or_404
from .models import Post
from .forms import PostForm
from django.contrib import messages
from django.http import JsonResponse

def post_index(request):
    posts = Post.objects.all() #veri tabanından getirdiğimiz değerler.
    return render(request,'post/index.html',{'posts':posts})


def post_detail(request,id):
    post = get_object_or_404(Post, id=id)


        # formdan gelen bilgileri kaydet

    context = {
        'post': post,

    }
    return render(request, 'post/detail.html', context)


def post_create(request):
    form =PostForm()
    context = {
        'form': form,
    }

    #if request.method == "POST":
    #   print(request.POST)

    if request.method == "POST":
        # formdan gelen bilgileri kaydet
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save()
            post.save()
            post.user = request.user
            messages.success(request, 'Başarılı bir şekilde oluşturdunuz....', extra_tags='mesaj-basarili')
            return HttpResponseRedirect(post.get_absolute_url())
    else:
        #formu kullanıcıya göster
        form = PostForm()
        context = {
             'form' :form,
        }

    #form = PostForm(request.POST or None)
    #if form.is_valid():
    #   form.save()
    #context = {
    #         'form' :form,
   #     }
    return render(request, 'post/form.html', context)


def post_update(request, id):

    post = get_object_or_404(Post, id=id)
    form = PostForm(request.POST or None, instance=post)

    if form.is_valid():
        form.save()
        messages.success(request, "Başarılı bir şekilde güncellediniz.")
        return HttpResponseRedirect(post.get_absolute_url())

    context = {
             'form': form
        }

    return render(request, 'post/form.html', context)

def post_delete(request, id=None):

    post = get_object_or_404(Post, id=id)
    if request.method=='POST':
        post.delete()
        return JsonResponse(data={'success':'silindi'})

home/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>

    <!-- En son derlenmiş ve minimize edilmiş CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<!-- Opsiyonel tema -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
<!-- En son derlenmiş ve minimize edilmiş JavaScript -->


    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% include 'header.html' %}

    {% include 'messages.html' %}

    {% block body %}

    {% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

home/templates/header.html
<!-- Navbar Start -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="banner">
    <div class="container">

        <div class="navbar-header">

            <!-- Telefon ekranları için menü butonu -->
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- İsim Soyisim veya Marka İsmi -->
            <a href="{% url 'home'%}" class="navbar-brand">Django Örnek Alıştırma</a>
        </div>

        <nav class="collapse navbar-collapse" role="navigation">

            <!-- Arama Çubuğu -->
            <form class="navbar-form navbar-left" role="search" method="GET" action="">
                <div class="input-group">
                    <input class="form-control" type="text" name="q" placeholder="Search on blog" value="" >
                    <span class="input-group-btn">
                        <input class="btn btn-default" type="submit" value="Ara">
                    </span>
                </div>
            </form>

            <!-- Temel Sayfalar -->
            <ul class="nav navbar-nav navbar-right">

                <li><a href="{% url 'post:create' %}">Kişi Ekle</a></li>

                <li><a href="{% url 'home'%}">Anasayfa</a></li>
                <li><a href="{% url 'post:index' %}">Liste</a></li>
                <li><a href="#">Hakkımda</a></li>
                <li><a href="#">İletişim</a></li>
            </ul>

        </nav>

    </div>
</nav>

home/templates/home.html
{% extends 'base.html' %}
{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-6" style="background-color: red">1.Sütun</div>
            <div class="col-md-6" style="background-color: blue">2.Sütun</div>
        </div>
    </div>
{% endblock %}

home/templates/messages.html
 {% if messages %}

        {% for message in messages %}
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                {{ message }}
        </div>
        {% endfor %}

 {% endif %}

home/templates/post/detail.html
{% extends 'base.html' %}
{% block body %}

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
        <div class="container">

            <div class="row">
              <div class="col-md-6 col-md-offset-3">
                <div class="thumbnail">
                  <div class="caption">

                    <h3><a>{{ post.name }}</a>  <a>{{ post.surname }}</a> <small>{{ post.recorded_date}}</small></h3>
                    <h4>Departmanı: {{ post.department }}</h4>
                        <p>{{ post.content|safe|linebreaks }}</p>
                        <p>
                    <p><a href="{{ post.get_absolute_url }}" class="btn btn-primary" role="button">İncele</a>
                        <a href="{{ post.get_update_url }}" class="btn btn-default" role="button">Güncelle</a>
                        <a href="{{ post.get_delete_url }}" class="btn btn-danger" role="button">Sil</a>

                    </p>
                  </div>
                </div>

              </div>
            </div>

        </div>
{% endblock %}

home/templates/post/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                    <form method="POST" enctype="multipart/form-data">

                                {% csrf_token %}
                                <h1>FORM</h1>
                                {{ form|crispy }}
                                <input class="btn btn-primary" type="submit" value="Gönder">

                    </form>

            </div>
        </div>
    </div>

{% endblock %}

home/templates/post/index.html
{% extends 'base.html' %}
{% block body %}

    <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js">
        $(document).ready(function (){
            $('.form-delete').submit(function (event){
                event.preventDefault();
                var form = $(this);
                var form_action = form.attr('action');
                var form_serialize =form.serialize();
                $.ajax({
                    method:'POST',
                    type:'json',
                    url:form_action,
                    data:form_serialize,
                    success:function (data){
                        console.log(data['success']);
                        form.parent().remove();
                    }
                })

            });

        });
    </script>


{# post/{{ post.id }} #}
{# {% url 'detail' id=post.id %} #}
<br><br><br><br>
    <div class="container">
    {% for post in posts %}
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <div class="thumbnail">
              <div class="caption">

                <h3>{{ post.name }}<small> {{ post.recorded_date|timesince }} önce</small></h3>
                <p>{{ post.surname }}</p>
                <h4>Departmanı: {{ post.department }}</h4>

                      <p>
                          <a href="{{ post.get_absolute_url }}" class="btn btn-primary" role="button">İncele</a>
                          <a href="{{ post.get_update_url }}" class="btn btn-default" role="button">Güncelle</a>
                          <form class="form-delete" method="POST" action="{% url 'post:delete' post.id %}">{% csrf_token %}
                            <input name="post_id" type="hidden" value="{{ post.id }}">
                            <input type="submit" class="btn btn-danger" role="button" value ='delete'></a>
                          </form>
                     </p>


              </div>
            </div>
          </div>
        </div>


    {% endfor %}
    </div>
{% endblock %}